version: '3.8'

services:
  db:
    image: mysql
    container_name: mysql
    restart: always
    tty: true
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    ports:
      - ${DB_PORT}:3306
    volumes:
      - ./back-end/.docker/dbdata:/var/lib/mysql