version: "3.8"

services:
  db:
    image: mysql
    container_name: mysql
    restart: always
    tty: true
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    ports:
      - ${DB_PORT}:3306
    volumes:
      - ./back-end/.docker/dbdata:/var/lib/mysql

  api:
    build: ./back-end
    container_name: api
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - API_PORT=${API_PORT}
      - EXPIRESIN=${EXPIRESIN}
      - JWT_KEY=${JWT_KEY}
    ports:
      - ${API_PORT}:${API_PORT}
    volumes:
      - ./back-end:/home/node/app
    depends_on:
      - db
    command: >
      bash -c "chmod +x .docker/wait-for-it.sh && ./.docker/wait-for-it.sh db:3306 -t 120 -- chmod +x .docker/entrypoint.sh && ./.docker/entrypoint.sh"

  web:
    container_name: vue3
    build:
      context: ./front-end
    ports:
      - "5173:5173"
    entrypoint: .docker/entrypoint.sh