### logIn
# @name login
POST http://localhost:3003/login
Content-Type: application/json 

{
    "email": "darmstadio@email.com",
    "password": "senhadodam"
}

###
@accessToken = Bearer {{login.response.body.accessToken}}

### SignIn
POST http://localhost:3003/user
Content-Type: application/json 

{
    "name": "Darmstadio",
    "email": "darmstadio@email.com",
    "password": "senhadodam",
    "role": "Customer"
}

### Get usert
GET http://localhost:3003/user/Adm
Authorization: {{accessToken}}

### Get Broker
GET http://localhost:3003/user/broker/2
Authorization: {{accessToken}}

### Get Costumer
GET http://localhost:3003/user/customer/1
Authorization: {{accessToken}}


### Update User
PATCH  http://localhost:3003/user/5
Authorization: {{accessToken}}
Content-Type: application/json 

{
    "name": "Email"
    # "emaill": "adeir@email.com",
    # "password": "senhadoadeir"

}

### Delete User
DELETE  http://localhost:3003/user/1
Authorization: {{accessToken}}


######################################################################################################

### Get Meetings by user
GET http://localhost:3003/meeting/user/3
Authorization: {{accessToken}}

### Get Meeting
GET http://localhost:3003/meeting/2
Authorization: {{accessToken}}

### Create Meeting
POST http://localhost:3003/meeting
Authorization: {{accessToken}}
Content-Type: application/json 

{
    "idBroker": 2,
    "idCustomer": 5,
    "startAt": "2023-12-03T15:40:12",
    "endAt": "2023-12-03T16:20:12"
}

### Update Meeting
PATCH  http://localhost:3003/meeting/5
Authorization: {{accessToken}}
Content-Type: application/json 

{
    "idBroker": 1,
    # "idCostumer": 2,
    "startAt": "2023-12-03T12:40:12"
    # "endAt": "2023-12-03T14:20:12"
}

### Delete Meeting
DELETE  http://localhost:3003/meeting/4
Authorization: {{accessToken}}

