### logIn
# @name login
POST http://localhost:3003/login
Content-Type: application/json 

{
    "email": "Darmstadio@email.com",
    "password": "senhadodan"
}

###
@accessToken = Bearer {{login.response.body.accessToken}}

### SignIn
POST http://localhost:3003/users
Content-Type: application/json 

{
    "name": "Darmstadio",
    "email": "Darmstadio@email.com",
    "password": "senhadodan",
    "role": "Broker"
}

### Update User
PATCH  http://localhost:3003/users/17
Authorization: {{accessToken}}
Content-Type: application/json 

{
    "name": "Da",
    "emaill": "Darmstadio@email.com",
    "password": "senhadodan"

}

### Delete User
DELETE  http://localhost:3003/users/17

